Began on curve-snake game
tsea83-g34/TSEA83_OperatingSystem pull request #23
Opened 2019-09-26 09:25 UTC by angloth

HMmm:

* 1
* 2
* 3

2019-09-26 09:27 UTC, Bence657 requested changes
* Fel
* Fel
* ojojoj

2019-09-26 09:27 UTC, Bence657 commented on user_programs/imperialism.cmm
> +int imperialism(){
Broooo this code is really bad

2019-09-26 09:28 UTC, Bence657 approved these changes
Ok!

2019-10-01 20:14 UTC, angloth commented
Test pull request, will be removed and closed

2019-10-01 20:14 UTC, closed without merging